version: '3.8'

services:
  postgres:
    image: postgres:15  # Используем официальный образ PostgreSQL
    environment:
      POSTGRES_USER: myuser  # Пользователь базы данных
      POSTGRES_PASSWORD: mypassword  # Пароль
      POSTGRES_DB: TaskManagement  # Имя базы данных
    ports:
      - "25432:5432"  # Экспонируем порт PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data  # Том для хранения данных
    restart: unless-stopped  # Перезапускать при сбое или перезагрузке
    
#  keycloak:
#    image: quay.io/keycloak/keycloak:20.0.2
#    container_name: keycloak
#    command:
#      - start --auto-build --db dev-file --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - 8282:8080
    
volumes:
  pgdata: